"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import sg_gui_builder

# Implementing MyFrame1
class sg_gui_builderMyFrame1( sg_gui_builder.MyFrame1 ):
	def __init__( self, parent ):
		sg_gui_builder.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def OnClose( self, event ):
		# TODO: Implement OnClose
		pass

	def OnButtonClickAddCW( self, event ):
		# TODO: Implement OnButtonClickAddCW
		pass

	def OnButtonClickGenerate( self, event ):
		# TODO: Implement OnButtonClickGenerate
		pass

	def OnButtonClickClearList( self, event ):
		# TODO: Implement OnButtonClickClearList
		pass


